CREATE DATABASE MENTOR;
USE MENTOR;
CREATE TABLE MENTOR_DETAILS(
MENTOR_ID INT PRIMARY KEY auto_increment,
MENTOR_NAME varchar(50),
MENTOR_AGE INT(3),
MENTOR_EMAIL varchar(20) unique,
MENTOR_DOB date
);
INSERT INTO MENTOR_DETAILS(MENTOR_NAME,MENTOR_AGE,MENTOR_EMAIL,MENTOR_DOB) VALUES ("JOTHI",22,"JOTHI@GMAIL.COM",curdate()); 
INSERT INTO MENTOR_DETAILS(MENTOR_NAME,MENTOR_AGE,MENTOR_EMAIL,MENTOR_DOB) VALUES ("JOTHI",22,"DIVYA@GMAIL.COM",curdate()); 
INSERT INTO MENTOR_DETAILS(MENTOR_NAME,MENTOR_AGE,MENTOR_EMAIL,MENTOR_DOB) VALUES ("JOTHI",22,"FAITHA@GMAIL.COM",curdate()); 

update MENTOR_DETAILS SET MENTOR_NAME="DIVYA" WHERE MENTOR_ID=2;
UPDATE MENTOR_DETAILS SET MENTOR_NAME="FAITHA" WHERE MENTOR_ID=3;
SELECT * FROM MENTOR_DETAILS;